# Generated by Django 3.1.7 on 2021-04-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_site_header',
            old_name='title',
            new_name='masthead',
        ),
    ]
