# Generated by Django 3.1.7 on 2021-04-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210413_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business_site_header',
            new_name='home_page',
        ),
    ]
