# Generated by Django 3.1.7 on 2021-04-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210413_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_page',
            old_name='descrition',
            new_name='description',
        ),
    ]
