# Generated by Django 3.1.7 on 2021-04-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210413_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='icon_1_description',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='icon_1_header',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='icon_2_description',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='icon_2_header',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='icon_3_description',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='icon_3_header',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_1_description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_1_header',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_1_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_2_description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_2_header',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_2_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_3_description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_3_header',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home_page',
            name='showcase_3_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='masthead',
            field=models.CharField(default='', max_length=30),
        ),
    ]
