# Generated by Django 3.1.7 on 2021-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210413_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='showcase_1_image',
            field=models.ImageField(blank=True, default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='showcase_2_image',
            field=models.ImageField(blank=True, default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='showcase_3_image',
            field=models.ImageField(blank=True, default='', upload_to='static/images'),
        ),
    ]
