# Generated by Django 3.1.7 on 2021-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210601_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='showcase_1_description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='showcase_2_description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='showcase_3_description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
